/**
 * Sri Sathya Sai Center/Group cities.
 * Use CITIES for dropdowns (Add Seva Activity, Manage Seva).
 * Use CENTERS_FOR_FILTER (includes "All") for filter dropdowns (Find Seva).
 */

const CITIES_SORTED = [
  "Anderson",
  "Ashburn",
  "Atlanta",
  "Auburn",
  "Austin",
  "Beavercreek TWP",
  "Bethesda",
  "Birmingham",
  "Bloomington",
  "Boulder",
  "Brevard",
  "Carmel",
  "Champaign-Urbana",
  "Charlotte",
  "Chattanooga",
  "Chicago",
  "Clearwater",
  "Cocoa Beach",
  "Colorado Springs",
  "Columbia",
  "Concord",
  "Dayton",
  "Edison",
  "Falls Church",
  "Fargo",
  "Flushing",
  "Fort Myers",
  "Fort Wayne",
  "Gainesville",
  "Germantown",
  "Greensboro",
  "Greenville",
  "Hillsborough Township",
  "Houston",
  "Howell Township",
  "Jackson",
  "Jacksonville",
  "Jersey City",
  "Johns Creek",
  "Lakewood Ranch",
  "Lansdale",
  "Livermore",
  "Madison",
  "Manassas",
  "Manhattan",
  "Mars Hill",
  "Medford",
  "Mesa",
  "MIAMI",
  "Mobile",
  "MONROE",
  "Morrisville",
  "New Hyde Park",
  "New Orleans",
  "North Canton",
  "Norwalk",
  "Oceanside",
  "Oshkosh",
  "Orlando",
  "Overland Park",
  "Palm Bay",
  "Phoenix",
  "Plano",
  "Powell",
  "Sacramento",
  "Salisbury",
  "Sammamish",
  "San Diego",
  "Scarborough",
  "Scottsdale",
  "Shelton",
  "St. Thomas",
  "Stockton",
  "Syracuse",
  "Tamarac",
  "Tampa",
  "Tustin",
  "Virginia Beach",
  "Warrington",
  "West Lafayette",
  "West Palm Beach",
  "White Plains",
  "Wilmington",
] as const;

export const CITIES = CITIES_SORTED;

/** For filter dropdowns (Find Seva): same list with "All" first */
export const CENTERS_FOR_FILTER = ["All", ...CITIES] as const;

export type City = (typeof CITIES)[number];
